[audio]
mp2k_hle_cubic = false
mp2k_hle_enable = false
interpolate_fifo = true
resampler = "cosine"
[video]
lcd_ghosting = true
color_correction = "ags"
filter = "nearest"
shader_fs = ""
scale = 2
shader_vs = ""
fullscreen = false

[cartridge]
force_rtc = false
save_type = "detect"

[input]
hold_fast_forward = true
fast_forward = 32
[input.gba]
b = 83
a = 65
select = 16777219
right = 16777236
r = 70
l = 68
left = 16777234
start = 16777220
down = 16777237
up = 16777235

[general]
sync_to_audio = false
bios_skip = false
bios_path = "bios.bin"

